### ISSUE TITLE
In GEOSwift,have a Class like "MinimumBoundingCircle" of JTS?

### ISSUE THREAD

**Issue by zhuyuping** [GEOSwift/GEOSwift#157]

**Comment by zhuyuping** [comment]
how can I count a MinimumBoundingCircle of a Polygon

**Comment by macdrevx** [comment]
@zhuyuping We don't have this yet. We'd need it to be exposed to GEOS's C API first. Here's a ticket that's tracking that: https://trac.osgeo.org/geos/ticket/735

**Comment by zhuyuping** [comment]
thanks~~I am waiting for update

**Comment by macdrevx** [comment]
@zhuyuping, I noticed you opened a few pull requests. We’re you planning to also contribute the code changes to add this feature? Typically, we wait to open PRs until those code changes are ready.

**Comment by zhuyuping** [comment]
I am sorry about an mistake that i make.In fact,I went planning to add some feature in GEOSwift Project.I want to push the new feature to my repo, but it is a mistake to push this repo.you can not ignore this mistake.I have a new direction to make a MIniCircleBounding class after your answer of issue 11.Thank you very much.
I want to contribute to this project in the future, but now I realize that my level of knowledge has not reached this level, sorry again.
I am sorry again because of the mistaken submission of the interference caused to you.

**Comment by macdrevx** [comment]
No worries. You’re welcome to contribute. Just trying to help. We’ll keep this feature request open, and hopefully it will get added to the geos C API soon so that we can adopt it in GEOSwift.

**Comment by macdrevx** [comment]
Looks like minimum bounding circle is going to ship with GEOS 3.8.0 which is just entering beta!

**Comment by macdrevx** [comment]
geos 3.8.0 has been released. To start using it in GEOSwift, we need to address to non-trivial issues:

https://github.com/GEOSwift/geos/issues/10
https://github.com/GEOSwift/geos/issues/11

The reason we need both of these is so that we don't break SPM support which currently depends on externally-maintained packages from apt & brew. Since we'll be requiring geos 3.8 or later and since we also want to support SPM on iOS and tvOS, we'll stop depending on external geos packages and start pulling in our own geos SPM-based package. This should also make for increased consistency between our CocoaPods, Carthage, and SPM configurations.
