### ISSUE TITLE
How to test if geometry is a Point?

### ISSUE THREAD

**Issue by Tybion** [GEOSwift/GEOSwift#169]
Thank you for all the work you have done upgrading the package, and the conversion guidelines at https://github.com/GEOSwift/GEOSwift/blob/master/VERSION_5.md are good.

But how do I convert the following code? ..
(Swift 5, Xcode 10.2)

```
            if geom is Waypoint {
                let pt = geom as! Waypoint
```

If I change the first line to ..
```
           if geom is Point {
```

.. I get the compile error
```
Cast from 'Geometry' to unrelated type 'Point' always fails
```

**Comment by macdrevx** [comment]
Geometry is now an enum, so you should be able to use `switch` or `if case let`:

```
if case let .point(pt) = geom {
    ...
```

Let me know if it works for you.

**Comment by Tybion** [comment]
Thanks, Andrew.

The compiler is happy with that.  I just need to get the rest of my code compiled before I can test that your suggestion above works.

Can you please also tell me how to change this ..
```
let feat = try Features.fromGeoJSON(url)   // (url is type URL)
```
In the Summary of API Changes, it mentions 

> FeatureCollection: Decodable

So I figure something like this ..
```
let feat = try FeatureCollection(from: <#T##Decoder#>)
```
.. but haven't been able to find doco or examples on Decodable

**Comment by macdrevx** [comment]
Decodable works with [JSONDecoder](https://developer.apple.com/documentation/foundation/jsondecoder). If you know that your GeoJSON is a feature collection, you can say:

```
let jsonData = try Data(contentsOf: url)
let decoder = JSONDecoder()
let featureCollection = try decoder.decode(FeatureCollection.self, from: jsonData)
```

The GeoJSON spec also [permits](https://tools.ietf.org/html/rfc7946#section-3) other top-level types (Feature, Geometry), so if you're not sure which top-level type you'll receive in your data, you should change the third line to read:

```
let geoJSON = try decoder.decode(GeoJSON.self, from: jsonData)
```

[GeoJSON](https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/Core%20Types/GeoJSON.swift) is an enum with associated values that has 3 cases: `featureCollection`, `feature`, and `geometry`. You can use the same techniques we discussed earlier to check which type you have and extract the associated value.

On the other hand, if you know for sure you'll only ever be decoding a specific GeoJSON type (say, polygon), you can also decode it directly to avoid the associated value extraction altogether:

```
let polygon = try decoder.decode(Polygon.self, from: jsonData)
```

Lastly, your v4 code was using the url-based [fromGeoJSON](https://github.com/GEOSwift/GEOSwift/blob/4.1.1/GEOSwift/GeoJSON.swift#L38) method. In version 5, we've separated the concerns of getting the data (could be from a file, from a web API, etc) and decoding it, which is why you now need to say `Data(contentsOf: url)` too.

**Comment by Tybion** [comment]
Thank you so much for your help, Andrew.

I have now got the app to the state where it is all compilable and runnable with Swift 5 and Xcode 10.3.  A fairly major job, with pod updates, code changes, etc.

I have a problem when reading a feature collection from a geoJSON file.  This is the code (from your suggestion above) ..

```
// Version 4 code ..
// let features = try Features.fromGeoJSON(url)

// GeoSwift 5 method instead ..
let decoder = JSONDecoder()
let jsonData = try Data(contentsOf: url)        // get the JSON data
featureCollection = try decoder.decode(FeatureCollection.self, from: jsonData)
features = featureCollection.features
```
I have pasted values read from the geoJSON file (from within the debugger) ..
```
Reading from geoJSON ..
features	[GEOSwift.Feature]	3365 values	
[0]	GEOSwift.Feature	
  geometry	GEOSwift.Geometry?	point
  properties	[String : GEOSwift.JSON]?	37 key/value pairs
  [0]	(key: String, value: GEOSwift.JSON)
    key	String	"ORE_GENESS"
    value	GEOSwift.JSON	null
  [1]	(key: String, value: GEOSwift.JSON)	
    key	String	"DESCRIPT"	
    value	GEOSwift.JSON	string
      string	String	"Small quarry providing silica and gravel."	
  [2]	(key: String, value: GEOSwift.JSON)	
    key	String	"PARENT_ID"	
    value	GEOSwift.JSON	null
```
2 problems ..
  * 'properties' is of type [String : GEOSwift.JSON] - I believe was previously [String: Any] - this is what I am retrieving from a SQLite file that was populated with the pre-version5 version of the app
  * within the 'properties' ALL numbers are NIL - ie. the number values have not been read

Can you please assist?

**Comment by macdrevx** [comment]
Can you share an example GeoJSON file that reproduces the problem?

**Comment by Tybion** [comment]
Rename back to .geojson ..
[TAS_constr_materials.txt](https://github.com/GEOSwift/GEOSwift/files/3487432/TAS_constr_materials.txt)

**Comment by Tybion** [comment]
I was wrong about all numbers being nil.  Numbers are being read OK.

**Comment by macdrevx** [comment]
Glad to hear it! Let me know if you run into anything else. I'm going to close this issue. Let's open separate tickets for future issues. That will make it easier for other people to find questions and answers that might help them.

**Comment by Tybion** [comment]
No, there is just **one problem** not two.

The code for reading the geoJSON is **not producing a Dictionary** for the 'properties  ie. [String: Any]

It is producing [String : GEOSwift.JSON]

How do I get the properties into a Dictionary?

**Comment by macdrevx** [comment]
Oops, sorry for misunderstanding.

In v4, properties had type `[String: Any]`. That worked b/c the implementation used `JSONSerialization`. This changed to `[String: JSON]` in v5 so that we could support `Codable`.

You should be able to update your code to extract the values you require from `JSON`. Similar to `Geometry` that we discussed earlier, [JSON is an enum](https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/Core%20Types/JSON.swift#L1) with associated values, so you can use the same techniques (if/guard/switch, case let) to extract specific values.

Can you share a little more info about how you're using the properties dictionary? That may help me guide you toward a solution a little more easily.

**Comment by Tybion** [comment]
I have found that this is how I am converting 'properties' to a NSDictionary ..
```
let attribs: NSDictionary = feature.properties! as NSDictionary
```
.. but I think the result might have changed with Swift 5, and it is not producing the right format for 

```
let data: Data = NSKeyedArchiver.archivedData(withRootObject: attribs) as Data
```

.. which is failing with this error ..

```
ausgeologymaps[277:48138] -[__SwiftValue encodeWithCoder:]:
                 unrecognized selector sent to instance 0x5fa42d0
```
Please leave this ticket closed.  I will investigate further and work out if this is a more general problem that should be on Stack Overflow.  Or if it is directly relevant to the GeoSwift conversion process, then I will create a new ticket here.

**Comment by Tybion** [comment]
Oops, crossed posts, just read your previous comment.  Yes, any help will be appreciated.

**Comment by Tybion** [comment]
I think this was probably what I was previously feeding to NSKeyedArchiver.archivedData ..
```
[0]	(key: String, value: Any)
key	String	"TAG"
value	Any	
payload_data_0	Builtin.RawPointer	0xbb31490	0x0bb31490 -> 0x386e8020 (void *)0x386e7ff8: __NSCFString
payload_data_1	Builtin.RawPointer	0xbb805b0	0x0bb805b0
payload_data_2	Builtin.RawPointer	0xe0bb8058
instance_type	Any.Type	0x0000000001b1cd9c  (__NSCFString?)

[1]	(key: String, value: Any)
key	String	"SCALE"	
value	Any	
payload_data_0	Builtin.RawPointer	0x17e0e200	0x17e0e200 -> 0x386e8070 (void *)0x386e8084: __NSCFNumber
payload_data_1	Builtin.RawPointer	0x36d8c	0x00036d8c
payload_data_2	Builtin.RawPointer	0xbbb5ed0	0x0bbb5ed0
instance_type	Any.Type	0x0000000001b231a0  (__NSCFNumber?)
```
.. and this is production so I can't change the format of the Data object being stored in the SQLite blob field to something else.

**Comment by macdrevx** [comment]
So one thing you could do is convert the `[String: JSON]` to `[String: Any]`. Can you try this code? If it works, let's consider adding it to the library as a convenience:

```
extension JSON {
    var wrappedValue: Any {
        switch self {
        case let .string(string):
            return string
        case let .number(number):
            return number
        case let .boolean(boolean):
            return boolean
        case let .array(array):
            return array.map { $0.wrappedValue }
        case let .object(object):
            return object.mapValues { $0.wrappedValue }
        case .null:
            return NSNull()
        }
    }
}

extension Feature {
    var unyptedProperties: [String: Any]? {
        return properties?.mapValues { $0.wrappedValue }
    }
}
```

to use it, you'll change

```
let attribs: NSDictionary = feature.properties! as NSDictionary
```

to

```
let attribs: NSDictionary = feature.untypedProperties! as NSDictionary
```

**Comment by Tybion** [comment]
Brilliant!  Thank you for being so responsive.
All looks good again.  Will also do some more testing with different geometry types.

Note there is a typo above - this is correct - says 'untyped' ..
```
extension Feature {
    var untypedProperties: [String: Any]? {
        return properties?.mapValues { $0.wrappedValue }
    }
}
```

**Comment by macdrevx** [comment]
Glad to hear it! I’ll look into adding this to the library in the next update.

**Comment by macdrevx** [comment]
@Tybion version 5.1 is now available and includes `Feature.untypedProperties` and `JSON.untypedValue`. Thanks for your help in identifying the need for these features!
