### ISSUE TITLE
Buffering point with specific SRID

### ISSUE THREAD

**Issue by sk-dataocean-online** [GEOSwift/GEOSwift#185]
I am trying to create buffer of a point but getting distorted ellipse instead of a circle:
![image](https://user-images.githubusercontent.com/40666974/66756761-5e426400-eea3-11e9-8ca0-e441ba7422b5.png)
It seems that I should set another SRID (seems like 3857 instead of 4326). Is it possible? I can't find any information on SRID in Geoswift.

**Comment by macdrevx** [comment]
There's no built-in support for SRID in GEOSwift. Even geos (the underlying library) [apparently](https://lists.osgeo.org/pipermail/geos-devel/2019-September/009258.html) doesn't do anything with SRID and at best just preserves the value from input to output. The FAQ on JTS (the Java library of which geos is a port) [addresses your question](http://www.tsusiatsoftware.net/jts/jtsfaq/jtsfaq.html#F):

> **F2. Can JTS be used to compute a geographically-accurate range circle ?**
>
> A geographically-accurate range circle is a shape on a spheroid modelling the surface of the Earth which is the boundary of the set of all points which are a given distance from a fixed point on the spheroid. This is a more complicated shape than either a circle or an ellipse. JTS cannot compute this shape, since JTS assumes a Cartesian coordinate system (i.e. a two-dimensional plane extending infinitely in all directions). This is not a good approximation to the surface of the spheroid, except over very small distances. Computing a true range circle requires complex spherical mathematics as well as a richer coordinate system model. This is outside the current scope of JTS.

Given this info, I think that GEOSwift might not be the best fit for the problem you're trying to solve. If you find a good alternative, should you share recommendations back here? This is a common question about GEOSwift especially since the project does offer some convenient integrations with MapKit.

**Comment by sk-dataocean-online** [comment]
I have only manual solution right now. It works only for point buffers and only for pseudo mercator proj 3857 (Google maps projection).

For each Y coordinate of buffered point (X0, Y0): new_Y = Y0 + (Y-Y0)*cos(Y*M_PI/180), where all coordinates are in degrees.

I didn't figure out how to apply scale factor for arbitrary buffers.

**Comment by macdrevx** [comment]
Thanks for sharing your solution. I’m going to close this issue since we don’t plan to support this in GEOSwift unless it’s someday added to geos.
