### ISSUE TITLE
Decoding GeoJSON

### ISSUE THREAD

**Issue by ssokol** [GEOSwift/GEOSwift#191]
This is more a question than an issue, but I'm having some challenges porting from v4 to v6, so...

My app pulls multiple GeoJSON strings from a database and uses GEOSwift to compare them with the current location (Coordinate) and forward vector (LineString) using the standard predicates. All of this worked in v4, but due to threading issues I've committed to moving up to the latest / greatest.

In v4, I was able to convert a GeoJSON string to a dictionary, then use `Geometry.fromGeoJSONDictionary(dictionary as Dictionary<String, AnyObject>)` to convert to an array of geometries. In v6 I can create a decoder and decode the GeoJSON, but only if I know ahead of time what geometry to expect (polygon, multi-polygon, etc.).

Is there a more generic way to decode from GeoJSON, as there was with v4? If not, what's the best approach to handle mixed-geometry data?

Any suggestions would be greatly appreciated. Sorry to be a clueless user.

(note: edited to remove error that seemed to go away after a clean / recompile)

**Comment by macdrevx** [comment]
Hi @ssokol, take a look at https://github.com/GEOSwift/GEOSwift/blob/master/GEOSwift/Core%20Types/GeoJSON.swift

If you decide to that type it should handle any valid GeoJSON.

**Comment by ssokol** [comment]
Thanks! But at the risk of exposing my woeful ignorance of modern Swift enums... What do you mean by "if you decide to that type"? 

Would the decode look like:

```
let mySomething = decoder.decode(GeoJSON.self, from: space.data)
```

From there, how do I know what the decoder decoded? In the v4 world the `fromGeoJSONDictionary` method always returned a sequence of Geometry objects that I could iterate over. What's the equivalent in v6 to do the same?

Apologies for my cluelessness - still learning the finer points of Swift.

**Comment by macdrevx** [comment]
Oops, I made a typo. Instead of “decide” it should have said “decode”.

You can use pattern matching with switch/if/guard to create variable bindings to the data inside the enum value. I’ll post an example when I’m back at my computer.

**Comment by macdrevx** [comment]
Okay, so here's an example:

According to the [spec](https://tools.ietf.org/html/rfc7946), the top-level GeoJSON object can either be a feature collection, a feature, or a geometry. The GEOSwift `GeoJSON` enum models this directly, so when you decode to that type, you then need to see which top-level type you received:

```
let mySomething = decoder.decode(GeoJSON.self, from: space.data)

switch mySomething {
case let .featureCollection(myFeatureCollection):
    // the variable myFeatureCollection is now bound to the associated data and is of type FeatureCollection
case let .feature(myFeature):
    // the variable myFeature is now bound to the associated data and is of type Feature
case let .geometry(myGeometry):
    // the variable myGeometry is now bound to the associated data and is of type Geometry
}
```

`FeatureCollection` and `Feature` are structs, but `Geometry` follows the same pattern as `GeoJSON`, so when/if you need to, you can access its associated data too using the same technique.

One nice thing about pattern matching is that you can compose patterns, so if, for example, you only cared about the case where the GeoJSON was a line string, you could write:

```
switch mySomething {
case let .geometry(.lineString(myLineString)):
    // the variable myLineString is now bound to the associated data and is of type LineString
default:
    // your data was of some other type
}
```

In the above situation you could also use guard:

```
guard let .geometry(.lineString(myLineString)) = mySomething else {
    // your data was of some other type
    return / throw / etc
}

// the variable myLineString is now bound to the associated data and is of type LineString
```

`if` works in a similar way.

One final gotcha about this is that if `mySomething` is optional (type `GeoJSON?` instead of `GeoJSON`), you'll need to either unwrap it before you switch/guard/if or incorporate that into the pattern matching. Here's what that would look like in the previous example:

```
guard let .some(.geometry(.lineString(myLineString))) = mySomething else {
    // your data was of some other type
    return / throw / etc
}

// the variable myLineString is now bound to the associated data and is of type LineString
```

**Comment by macdrevx** [comment]
You can read more about [enums with associated values in the Swift docs](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html#ID148).

**Comment by ssokol** [comment]
@macdrevx - thank you very much! I knew that enums were more than collections of named constants, but I really had not delved into the associated value bit at all. Your examples are awesome - I now get it!

I'm going to close this, but you might want to consider tossing those examples into the VERSION_5.md file for posterity.

**Comment by macdrevx** [comment]
Glad this helped. I've updated the VERSION_5 doc based on your recommendation: https://github.com/GEOSwift/GEOSwift/blob/master/VERSION_5.md#common-questions
