### ISSUE TITLE
import module error - when added to the podfile of a pod framework

### ISSUE THREAD

**Issue by siddharthan64** [GEOSwift/GEOSwift#75]
I'm trying to pod install `GEOSwift` into my project's (lets say child xcodeproj) parent project (lets say Parent xcodeproj).

Child .xcodeproj has its own podfile where I have added RxSwift, RxCocoa, Realm and this GeoSwift library. Here is the cocoapods file as show below

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, "9.0"
    inhibit_all_warnings!
    use_frameworks!
    
    project 'LocationManager/LocationManager'
    
    def pods 
    
        pod 'GEOSwift'
        pod 'RxSwift', '~> 4.0'
        pod 'RxCocoa', '~> 4.0'
        pod 'RealmSwift', '~> 3.0'
    end
    
    target 'LocationManager' do
        
        pods
    
        target 'LocationManagerTests' do
        
            inherit! :search_paths
        
            pod 'RxBlocking', '~> 4.0'
            pod 'RxTest', '~> 4.0'
        end
    end

This LocationManager is installed into another `XCode` project as another podfile

    def location_pods
       pod 'GEOSwift'
            
            
       pod 'LocationManager', :git => 'git@github.com:myrepo/locationmanager.git', :branch => 'users/me/add-geoswift'
    
    end
    
    target 'TestApp' do
       
       location_pods
    
       project 'TestApp.project'
    end
When I try to compile the TestApp target, XCode throws an error as below
[![enter image description here][2]][2]
GeoSwift module is not found. This error is inside the `Pods > LocationManager > MockLocationManager.swift` The same module imported else where in that `Pods > LocationManager` works. Also `import RxSwift` and `import RxCoca` works. When I accessed `Pods > Targets > LocationManager > Build Phases > Target Dependencies` I see all the pods except GeoSwift
[![enter image description here][3]][3]

May I know how to fix this issue? Adding `GeoSwift` to this targetDependency doesn't compile either. When compiling `LocationManager.xcworkspace` as a separate entity it works perfectly fine. That module `import GeoSwift` doesn't throw any compilation error.

  [2]: https://i.stack.imgur.com/uJeU3.png
  [3]: https://i.stack.imgur.com/r2gBL.png

**Comment by vfn** [comment]
@siddharthan64 can you please post the output of `pod install`?

**Comment by derickito** [comment]
I have the same issue. Here's the output of pod update:

Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/erickdelorbe/.cocoapods/repos/master fetch origin
  --progress
  $ /usr/bin/git -C /Users/erickdelorbe/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/erickdelorbe/.cocoapods/repos/master reset --hard
  origin/master
  HEAD is now at 1e7eade4e34 [Add] Atributika 4.4.1

CocoaPods 1.5.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0.beta.1

Analyzing dependencies
Downloading dependencies
Installing Alamofire 4.7.1 (was 4.7.0)
Installing GEOSwift (2.1.3)
Installing geos (3.5.0)
[!] /bin/bash -c 
set -e
type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

sed -i "" "s/\/\* #undef HAVE_INT64_T_64 \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h
sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\* #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h

cat <<EOT >> include/geos/platform.h
  #undef ISNAN
  #define ISNAN(x) (std::isnan(x))
EOT

patch capi/geos_c.h <<EOF
  149c149
  < #include <geos/export.h>
  ---
  > #define GEOS_DLL
EOF

/bin/bash: line 4: alias: aclocal: not found
/bin/bash: line 4: alias: xcrun aclocal: not found


[!] Automatically assigning platform `ios` with version `11.3` on target `HARCarMode` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by vfn** [comment]
@derickito the issue on your case is a missing dependency `aclocal`, that's pointed out on the last few lines of the output.

**Comment by macdrevx** [comment]
@siddharthan64 if this is still not working for you, please reopen this issue. You may also want to try out version 3.0.0 of GEOSwift which was just released.
